name: C.I. Workflow

on:
    push:
        branches: [master]
        paths-ignore:
            - "./package.json"
            - "./CHANGELOG.md"
    pull_request:
        branches: [master]
    create:
        tags:
            - "v*"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build --if-present

            - name: Bump version and push tag
              if: github.event_name == 'push'
              uses: TriPSs/conventional-changelog-action@v3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  git-message: "chore(release): {version}"
                  release-count: 10

            - name: Deploy
              if:
                  github.event_name == 'create' && github.event.ref_type ==
                  'tag'
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: build
                  CLEAN: true
